In [1]:
import numpy as np

In [5]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
%timeit my_arr2 = my_arr * 2

1.83 ms ± 4.02 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
%timeit my_list2 = [x * 2 for x in my_list]

37.6 ms ± 666 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
a = [
    [2, 2.2, 2.22],
    [3, -3, 0]
]

data =np.array(a)
print(data)

[[ 2.    2.2   2.22]
 [ 3.   -3.    0.  ]]


In [18]:
print(data * 10)
print(data + data)
print(data / data)

[[ 20.   22.   22.2]
 [ 30.  -30.    0. ]]
[[ 4.    4.4   4.44]
 [ 6.   -6.    0.  ]]
[[ 1.  1.  1.]
 [ 1.  1. nan]]


C:\Users\이시운\AppData\Local\Temp\ipykernel_35744\2481136603.py:3: RuntimeWarning: invalid value encountered in divide
  print(data / data)


In [22]:
print(data.shape)
print(type(data))
print(data.dtype)

(2, 3)
<class 'numpy.ndarray'>
float64


### 1.1 ndarray 생성

In [24]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9.9]
arr = np.array(my_list)
print(arr)

[1.  2.  3.  4.  5.  6.  7.  8.  9.9]


In [25]:
my_list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(my_list2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
print(arr.dtype)
print(arr2.dtype)

float64
int64


In [27]:
print(arr.ndim)
print(arr2.ndim)

1
2


In [28]:
print(arr.shape)
print(arr2.shape)

(9,)
(2, 4)


In [34]:
print(np.zeros(10))
print(np.empty(10))
print(np.zeros((5, 5)))
print(np.empty((5, 5)))
print(np.zeros((2, 3, 4)))
print(np.empty((2, 3, 4)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [36]:
print(np.arange(5))

[0 1 2 3 4]


### 1.2 자료형

In [40]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int8)

print(arr1.dtype)
print(arr2.dtype)


float64
int8


In [43]:
arr = np.array([1, 2, 3, 4, 5])
float_arr = arr.astype(np.float32)
print(arr)
print(float_arr)
print(float_arr.dtype)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
float32


In [44]:
arr = np.array([1, 2.2, -3.3, -4, -5])
int_arr = arr.astype(np.int32)
print(int_arr)

[ 1  2 -3 -4 -5]


In [47]:
arr = np.array(['1', '2', '3'])
int_arr = arr.astype(np.int32)
print(int_arr)

[1 2 3]


In [53]:
a = [[1, 2, 3], [4, 5, 6]]
b = [[5, 6, 7], [2, 3, 4]]
arr_a = np.array(a)
arr_b = np.array(b)
print(arr_a > arr_b)

[[ True False  True]
 [False  True False]]


### 1.4 인덱싱, 슬라이싱

In [63]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[3:5])


arr[3:6] = 0
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[3 4]
[0 1 2 0 0 0 6 7 8 9]


In [64]:
#슬라이싱을 해도 원본을 들고있음 (기본 슬라이싱은 별도)
slice_arr = arr[:]
slice_arr[0] = 100
print(arr)

[100   1   2   0   0   0   6   7   8   9]


In [65]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(a)

In [68]:
print(arr[0][1])
print(arr[0, 1])

2
2


In [103]:
a = [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
        ]
]
arr = np.array(a)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [104]:
print(arr[0])
print(arr[0, 0])
print(arr[0, 0][0])

[[1 2 3]
 [4 5 6]]
[1 2 3]
1


In [105]:
print(arr[0][0:1][:])

[[1 2 3]]


In [106]:
arr2d = np.arange(1, 10).reshape(3, 3)

In [107]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [95]:
print(arr[0][0:1][:])

[[1 2 3]]


In [110]:
arr2d[:, :1] =100
print(arr2d)

[[100   2   3]
 [100   5   6]
 [100   8   9]]


### bool 값으로 선택

In [143]:
names = ['a', 'b', 'a', 'c']
scores = [
    ['지', 100],
    ['수', 90],
    ['화', 80],
    ['풍', 70],
]
names_arr = np.array(names)
scores_arr = np.array(scores)
print(names_arr)
print(scores_arr)

['a' 'b' 'a' 'c']
[['지' '100']
 ['수' '90']
 ['화' '80']
 ['풍' '70']]


In [144]:
names_arr == 'a'

array([ True, False,  True, False])

In [145]:
scores_arr[names_arr == 'a', 1:]

array([['100'],
       ['80']], dtype='<U21')

In [146]:
print(names_arr != 'a')
print(~(names_arr == 'a'))

[False  True False  True]
[False  True False  True]


In [147]:
cond = names_arr == 'c'
print(cond)
scores_arr[cond]

[False False False  True]


array([['풍', '70']], dtype='<U21')

In [148]:
cond = (names_arr == 'c') | (names_arr =='a')
scores_arr[cond]

array([['지', '100'],
       ['화', '80'],
       ['풍', '70']], dtype='<U21')

### 1.6 팬시 인덱싱(fancy indexing)

In [158]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [162]:
print(arr[[0, 3, 2, -1, -6]])

[[ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]
 [28 29 30 31]
 [ 8  9 10 11]]


In [169]:
arr[[3, 2, 1],[3, 2, 1]]

array([15, 10,  5])

### 1.7 전치 

In [172]:
# 뒤집기
arr = np.arange(15).reshape(3, 5)
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [177]:
# 행렬의 곱
print(np.dot(arr, arr.T))
print(arr @ arr.T)

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [180]:
sample = np.random.standard_normal(size=(4, 4))
print(sample)

[[ 0.38659812 -0.36786145  0.75038294  1.15493519]
 [-1.85617026 -0.12810147 -0.09737473 -1.11458708]
 [ 1.27642303 -1.64106709 -0.64620304  0.92524359]
 [ 0.42736548 -0.53015431  0.39322255 -1.45818335]]


In [182]:
print(np.sqrt(sample))
# nan : nor a number

[[0.62177015        nan 0.86624647 1.07467911]
 [       nan        nan        nan        nan]
 [1.12978893        nan        nan 0.96189583]
 [0.65373196        nan 0.6270746         nan]]


C:\Users\이시운\AppData\Local\Temp\ipykernel_35744\724543005.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(sample))


In [183]:
# 절댓값
print(np.abs(sample))

[[0.38659812 0.36786145 0.75038294 1.15493519]
 [1.85617026 0.12810147 0.09737473 1.11458708]
 [1.27642303 1.64106709 0.64620304 0.92524359]
 [0.42736548 0.53015431 0.39322255 1.45818335]]


In [185]:
np.isnan(np.sqrt(sample))

C:\Users\이시운\AppData\Local\Temp\ipykernel_35744\619758985.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.isnan(np.sqrt(sample))


array([[False,  True, False, False],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [False,  True, False,  True]])

In [192]:
np.isnan(np.sqrt(sample)) * np.sqrt(sample)

C:\Users\이시운\AppData\Local\Temp\ipykernel_35744\3430129066.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.isnan(np.sqrt(sample)) * np.sqrt(sample)


array([[ 0., nan,  0.,  0.],
       [nan, nan, nan, nan],
       [ 0., nan, nan,  0.],
       [ 0., nan,  0., nan]])

In [196]:
import random
position = 0
walk = [position]
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
walk_arr = np.array(walk)
print(walk_arr)

[0 1 2 ... 4 3 2]


In [197]:
### 시각화 m

In [199]:
import matplotlib.pyplot as plt
plt.figure()

<Figure size 640x480 with 0 Axes>

<Figure size 640x480 with 0 Axes>

In [204]:
plt.plot(walk_arr[:100])
plt.show()

In [205]:
print(walk_arr[:100].max())
print(walk_arr[:100].min())


16
-5


In [207]:
print((walk_arr[:100] >= 5) .argmax())

49
