In [1]:
import pandas as pd

## Series
1차원 배열

In [2]:
import numpy as np
arr = np.arange(100, 110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [3]:
s =pd.Series(arr)
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [84]:
s = pd.Series(arr, dtype='int32')
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int32


In [85]:
s = pd.Series(['a', 'b', 'c', 'd'])
print(s)

0    a
1    b
2    c
3    d
dtype: object


### indexing

In [86]:
person = ['aa', 'bb', 'cc', 'dd']
s = pd.Series(person)
print(s)

0    aa
1    bb
2    cc
3    dd
dtype: object


In [87]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [88]:
s[1]
# s[-1] 불가

'bb'

In [89]:
s = pd.Series(person, index=['a', 'b', 'c', 'd'])
s = pd.Series(person, index=list('abcd'))
print(s)

a    aa
b    bb
c    cc
d    dd
dtype: object


In [90]:
s['a']
# s[0] 사라짐

'aa'

In [91]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [92]:
s.values

array(['aa', 'bb', 'cc', 'dd'], dtype=object)

In [93]:
s.ndim

1

In [94]:
s.shape

(4,)

### NaN(Not a Number) 결측치

In [95]:
s = pd.Series(person + [np.nan])
print(s)

0     aa
1     bb
2     cc
3     dd
4    NaN
dtype: object


In [96]:
arr = np.arange(50, 55)
s = pd.Series(arr, dtype='float32')
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [97]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


In [98]:
s[['다', '나']]

다     사과
나    NaN
dtype: object

In [99]:
s.iloc[[2, 3]]
s[['다', '라']]

다    사과
라    포도
dtype: object

### bool

In [100]:
s[[True, False, False, True, True]] 
arr = np.arange(5,20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [101]:
s < 10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [102]:
s[s < 10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [103]:
ss = s[s ==5]
ss[0] = 100
print(s)
print(ss)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64
0    100
dtype: int64


### 결측치 처리

In [104]:
s = pd.Series([2, 5, 3, 5, np.nan, 3, 5, 3, np.nan])

In [105]:
s.isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
dtype: bool

In [106]:
s[s.isnull()]
s[s.isna()]

4   NaN
8   NaN
dtype: float64

In [107]:
s[s.notnull()]
s[s.notna()]

0    2.0
1    5.0
2    3.0
3    5.0
5    3.0
6    5.0
7    3.0
dtype: float64

In [108]:
s[1:3]

1    5.0
2    3.0
dtype: float64

# DateFrame
2차원에 적합

In [109]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [114]:
df = pd.DataFrame(
    arr,
    columns=['가', '나', '다'],
    index=['a', 'b', 'c'])
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [117]:
data = {
    'name': ['kim', 'lee', 'park'],
    'age': [10, 15, 20],
    'location':['seoul', 'paju', 'LA'],
}
df = pd.DataFrame(data)
df

name  age location
0   kim   10    seoul
1   lee   15     paju
2  park   20       LA

In [120]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [122]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [139]:
df.T
#원본지지

a     b     c
name        kim   lee  park
age          10    15    20
location  seoul  paju    LA

In [124]:
df.index = list('abc')
df

name  age location
a   kim   10    seoul
b   lee   15     paju
c  park   20       LA

### column

In [126]:
df['name']

a     kim
b     lee
c    park
Name: name, dtype: object

In [130]:
type(df['name'])

pandas.core.series.Series

In [131]:
df[['name', 'location']]

name location
a   kim    seoul
b   lee     paju
c  park       LA

In [132]:
type(df[['name', 'location']])

pandas.core.frame.DataFrame

In [134]:
df[['name']]
type(df[['name']])

pandas.core.frame.DataFrame

In [151]:
df.rename(columns={'location': 'hometown'})
#원본유지
df.rename(columns={'location': 'hometown'}, inplace=True)
#원본 inplace
print(df)

   name  age hometown
a   kim   10    seoul
b   lee   15     paju
c  park   20       LA
